### ISSUE TITLE
address and address on participants view

### ISSUE THREAD

**Issue by Floraachr** [NeuroDevComp/babylab-redcap#17]
We have two "address" on the participant view, I think one is for the address and the other is for the postal code?
Also, we don't have the city name  it's just written "city :"

**Comment by gongcastro** [comment]
You're right, the "Address" label should be replaced by "Postcode" in the second instance. The "City" field is empty because there is not data (it is not a mandatory item, so it can be left blank).

- [ ] Replace label "Address" with "Postcode"
- [ ] Prepend field labels to actual text for easier reading.
