### ISSUE TITLE
Plotting participants vs. appointments

### ISSUE THREAD

**Issue by Floraachr** [NeuroDevComp/babylab-redcap#4]
What should we say is a "participant" for our data analyses (the fancy dashboard)

Shouldn't a "participant" be a successful appointment ? --> A baby who came and participated to the study (Not necessarily a keeper though) 

Because I can see that we have 43 participants and 39 appointments, meaning that not all babies have participated so I think they shouldn't be taken into account when analyzing the age, sex, influx and others demographics, no? 

What's interesting in influx and appointments is to see the difference between the number of appointments made and the ones actually done OR the number of baby we have and the number of appointments confirmed.

**Comment by gongcastro** [comment]
That's a good point. Regarding the main dashboard, I think it is relevant to see the characteristics of the participants in our database, regardless of whether they have participated already or not. Either way we could add other plots to the dashboard showing some characteristics of the participants breaking down the number of participations.

Regarding the study-specific dashboard, I agree that the relevant unit of observation should be the "successful" appointment. Since we are not running longitudinal studies (yet) a successful appointment should translate into one datapoint in our study dataset (which in the end is what we care about). We might accordingly only show info about successful appointments.

I can definitely make a plot with the number of confirmed vs. successful appointments. Could you describe more specifically how you'd like to find that info in a plot? In general, I'd be happy to add any plot/table/info you think would be useful to see. :smile:

**Comment by gongcastro** [comment]
Closing for now until specific requests for plots are made (we can have a meeting some time later!).
